create table short_videos (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    summary text not null,
    video_key varchar(255) not null,
    thumbnail_key varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_short_videos_video_key unique (video_key)
);

create table short_video_scenes (
    id bigint generated by default as identity primary key,
    short_video_id bigint not null,
    scene_index integer not null,
    start_time numeric(10, 3) not null,
    end_time numeric(10, 3) not null,
    duration numeric(10, 3) not null,
    origin_script text not null,
    image_url text not null,
    constraint fk_short_video_scenes_short_video
        foreign key (short_video_id)
        references short_videos (id)
        on delete cascade
);

create table short_video_code_blocks (
    id bigint generated by default as identity primary key,
    short_video_id bigint not null,
    title varchar(255) not null,
    code text not null,
    sort_order integer not null,
    constraint fk_short_video_code_blocks_short_video
        foreign key (short_video_id)
        references short_videos (id)
        on delete cascade
);

create index idx_short_video_scenes_short_video_id
    on short_video_scenes (short_video_id);

create index idx_short_video_code_blocks_short_video_id
    on short_video_code_blocks (short_video_id);
