package com.swiftly.swiftlyserver.internal.n8n

import com.fasterxml.jackson.annotation.JsonProperty
import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Pattern

@Schema(description = "Short-form video metadata generated by the n8n workflow.")
data class N8nShortIngestRequest(
    @field:NotBlank
    val title: String,
    @field:NotBlank
    val summary: String,
    @get:JsonProperty("video_key")
    @param:JsonProperty("video_key")
    @field:NotBlank
    @field:Pattern(regexp = "^videos/.+", message = "must start with videos/")
    val videoKey: String,
    @get:JsonProperty("thumbnail_key")
    @param:JsonProperty("thumbnail_key")
    @field:NotBlank
    @field:Pattern(regexp = "^thumbnails/.+", message = "must start with thumbnails/")
    val thumbnailKey: String,
    @field:Valid
    val codeBlocks: List<N8nCodeBlockRequest> = emptyList(),
)

data class N8nCodeBlockRequest(
    @field:NotBlank
    val title: String,
    @field:NotBlank
    val code: String,
)
