package com.swiftly.swiftlyserver.internal.n8n

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.ExampleObject
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.security.SecurityRequirement
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import io.swagger.v3.oas.annotations.parameters.RequestBody as OpenApiRequestBody

@Validated
@RestController
@RequestMapping("/internal/n8n/shorts")
@Tag(name = "Internal n8n shorts ingest")
@SecurityRequirement(name = "n8nIngestToken")
class N8nShortIngestController(
    private val n8nShortIngestService: N8nShortIngestService,
) {
    @PostMapping
    @Operation(
        summary = "Upsert short-form video metadata generated by n8n.",
        requestBody =
            OpenApiRequestBody(
                required = true,
                content = [
                    Content(
                        schema = Schema(implementation = N8nShortIngestRequest::class),
                        examples = [
                            ExampleObject(
                                value = """
                                [
                                  {
                                    "title": "CarPlay 앱을 더 강력하게 만들기",
                                    "summary": "iOS 26의 CarPlay 업데이트를 짧게 소개합니다.",
                                    "video_key": "videos/83Vb0OHpsfJ6vQVFLEhpL_output.mp4",
                                    "thumbnail_key": "thumbnails/YaT65dxlPRu5pqruhQkoE_first_frame.jpg",
                                    "duration_seconds": 78,
                                    "codeBlocks": [
                                      {
                                        "title": "Set CarPlay as a disfavored location",
                                        "code": "WidgetConfiguration().disfavoredLocations([.carPlay], for: [.systemSmall])"
                                      }
                                    ]
                                  }
                                ]
                                """,
                            ),
                        ],
                    ),
                ],
            ),
    )
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "Short metadata was created or updated."),
            ApiResponse(responseCode = "400", description = "Invalid n8n payload."),
            ApiResponse(responseCode = "401", description = "Missing or invalid ingest token."),
        ],
    )
    fun ingestShorts(
        @Valid @RequestBody requests: List<@Valid N8nShortIngestRequest>,
    ): N8nShortIngestResponse = n8nShortIngestService.ingest(requests)
}
