package com.swiftly.swiftlyserver.internal.n8n

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.security.SecurityRequirement
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@Validated
@RestController
@RequestMapping("/internal/n8n/shorts")
@Tag(name = "Internal n8n shorts ingest")
@SecurityRequirement(name = "n8nIngestToken")
class N8nShortIngestController(
    private val n8nShortIngestService: N8nShortIngestService,
) {
    @PostMapping
    @Operation(summary = "Upsert short-form video metadata generated by n8n.")
    fun ingestShorts(
        @Valid @RequestBody requests: List<@Valid N8nShortIngestRequest>,
    ): N8nShortIngestResponse = n8nShortIngestService.ingest(requests)
}
