package com.swiftly.swiftlyserver.internal.n8n

import com.fasterxml.jackson.annotation.JsonProperty
import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.Valid
import jakarta.validation.constraints.AssertTrue
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Pattern
import java.math.BigDecimal

@Schema(description = "Short-form video metadata generated by the n8n workflow.")
data class N8nShortIngestRequest(
    @field:NotBlank
    val title: String,
    @field:NotBlank
    val summary: String,
    @get:JsonProperty("video_key")
    @param:JsonProperty("video_key")
    @field:NotBlank
    @field:Pattern(regexp = "^videos/.+", message = "must start with videos/")
    val videoKey: String,
    @get:JsonProperty("thumbnail_key")
    @param:JsonProperty("thumbnail_key")
    @field:NotBlank
    @field:Pattern(regexp = "^thumbnails/.+", message = "must start with thumbnails/")
    val thumbnailKey: String,
    @field:Valid
    val codeBlocks: List<N8nCodeBlockRequest> = emptyList(),
    @field:Valid
    val scenes: List<N8nSceneRequest> = emptyList(),
)

data class N8nCodeBlockRequest(
    @field:NotBlank
    val title: String,
    @field:NotBlank
    val code: String,
)

data class N8nSceneRequest(
    @get:JsonProperty("scene_index")
    @param:JsonProperty("scene_index")
    @field:Min(1)
    val sceneIndex: Int,
    @get:JsonProperty("start_time")
    @param:JsonProperty("start_time")
    @field:DecimalMin("0.0")
    val startTime: BigDecimal,
    @get:JsonProperty("end_time")
    @param:JsonProperty("end_time")
    @field:DecimalMin("0.0")
    val endTime: BigDecimal,
    @field:DecimalMin("0.0", inclusive = false)
    val duration: BigDecimal,
    @get:JsonProperty("origin_script")
    @param:JsonProperty("origin_script")
    @field:NotBlank
    val originScript: String,
    @get:JsonProperty("image_url")
    @param:JsonProperty("image_url")
    @field:NotBlank
    val imageUrl: String,
) {
    @AssertTrue(message = "end_time must be greater than start_time")
    fun isValidTimeRange(): Boolean = endTime > startTime
}
